allow to skip `plot_show()` to be able to get the current axis
WillianFuks/tfcausalimpact pull request #13
Opened 2021-03-15 14:21 UTC by kjappelbaum

Hi, thanks for this great library!

This PR does not do much, it only allows that users can get the current matplotlib axis to change the style of the plot or to save the figure. That is, it should also address dafiti/causalimpact#72.

Using the show argument is similar to what, for example, SHAP does https://github.com/slundberg/shap/blob/3711be957461c3747d4f788e8604c5568ffb2d90/shap/plots/_violin.py#L19-L27

2021-03-15 15:56 UTC, WillianFuks requested changes
Hi @kjappelbaum , thanks for this PR!

I'd like to ask you for a few things:

1. Could you please add unit tests for the scenario where `show=False`? Tests are run with tox, you can send arguments such as `tox -e py38 -- tests/test_plot.py`. Just one extra test should do it.
2. This new variable should be available on the CausalImpact client's method [`plot`](https://github.com/kjappelbaum/tfcausalimpact/blob/plot-show-optional/causalimpact/main.py#L223-L227) otherwise we can't use is yet.
3. Users should have access to the axis by `import matplotlib`? One thing we could also do is `return ax`, not sure if this would work as intended though.

Best,

Will

2021-03-15 15:56 UTC, WillianFuks commented on causalimpact/plot.py
> +        If true, runs plt.show(), i.e., displays the figure. Defaults to True.
We could also explain why this is used, that is, when `show=False` the client can have access to the axis.

2021-03-17 23:35 UTC, kjappelbaum commented
Hi Will, 

thanks for review and comments :) 
I'd hesitate to have a toggle on the return type of a function, i think `plt.gcf()` or `plt.gca()` should do the the job. 

Cheers,
Kevin

2021-03-18 00:38 UTC, WillianFuks commented
Sounds great! I'll prepare to finish the PR now :)!

2021-03-18 13:55 UTC, merged